# Generated by Django 3.1.1 on 2020-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201005_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='check',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
