# Generated by Django 3.1.1 on 2020-10-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
