# Generated by Django 2.1.15 on 2020-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detects', '0002_auto_20200922_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
