<template>
  <div class="main">
    <Nav />

    <div class="menu">
      <div>
        <router-link to="/createList" style="text-decoration:none">
          <div class="icons">
            <img src="@/assets/frame.png" width="170px" height="170px;" />
          </div>
          <p>명부 작성</p>
        </router-link>
      </div>

      <div>
        <div @click="test">
          <div class="icons">
            <img src="@/assets/frame.png" width="170px" height="170px;" />
          </div>
          <p>TEST</p>
        </div>
      </div>
      
      <div>
        <router-link to="/account" style="text-decoration:none">
          <div class="icons">
            <img src="@/assets/key.png" width="170px" height="170px;"/>
          </div>
          <p>
          계정 설정
          </p>
        </router-link>
      </div>
      <div id="image-area">
        hello,,,>??
      </div>
    </div>
  </div>
</template>

<script>
import Nav from "@/components/Nav.vue";
import axios from 'axios'
export default {
  name: "Main",
  components: {
    Nav,
  },
  methods: {
    test() {

        function b64toBlob(b64Data, contentType, sliceSize) {
                contentType = contentType || '';
                sliceSize = sliceSize || 512;

                var byteCharacters = atob(b64Data);
                var byteArrays = [];

                for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
                    var slice = byteCharacters.slice(offset, offset + sliceSize);

                    var byteNumbers = new Array(slice.length);
                    for (var i = 0; i < slice.length; i++) {
                        byteNumbers[i] = slice.charCodeAt(i);
                    }

                    var byteArray = new Uint8Array(byteNumbers);

                    byteArrays.push(byteArray);
                }

              var blob = new Blob(byteArrays, {type: contentType});
              return blob;
        }
      console.log('test video')
      axios.get('http://127.0.0.1:8000/cam/video/')
        .then((res) => {
          console.log("전송성공")
          this.result = res.data
          console.log(this.result)
          alert('응답왔어용')
          var image = new Image()
          var realData = 'iVBORw0KGgoAAAANSUhEUgAAAaUAAAJ4CAYAAADFmvzCAAAXtUlEQVR4Xu3VQQ0AAAwCseHf9Gzco1NAyhJ2jgABAgQIRAQWySEGAQIECBA4o+QJCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIGCU/QIAAAQIZAaOUqUIQAgQIEDBKfoAAAQIEMgJGKVOFIAQIECBglPwAAQIECGQEjFKmCkEIECBAwCj5AQIECBDICBilTBWCECBAgIBR8gMECBAgkBEwSpkqBCFAgAABo+QHCBAgQCAjYJQyVQhCgAABAkbJDxAgQIBARsAoZaoQhAABAgSMkh8gQIAAgYyAUcpUIQgBAgQIPFy8AnmGdUh9AAAAAElFTkSuQmCC'
          image.src = 'data:image/png;base64,' + res.data['capture']
          var blob = b64toBlob(realData, 'image/png');
          document.body.appendChild(blob);
          document.getElementById('image-area').appendChild(image)
        })
        .catch((err) => {
          console.log('사진 업로드 실패', err)
        })
    },
  }          
}
</script>

<style scoped>
  .menu {
    position : fixed;
    top : 42%;
    width: 30%;
    text-align: center;
    padding: 0 35% 0 35%;
    display: flex;
    z-index: 2;
    justify-items: center;
    justify-content: space-between;
  }
  .icons {
    height : 180px;
  }
  img {
    transform: scale(1);
    -webkit-transform:scale(1);
  }
  img:hover {
    transform: scale(1.2);
    -webkit-transform:scale(1.2);
  }
  p {
    color : white;
  }
</style>
